### ISSUE TITLE
possible moves missing (0:38), disappearing of black pawn

### ISSUE THREAD

**Issue by alansmathew** [madhaven/Chess.AI#1]
after certain moves, from the left most place. then cutting into one black will cause the position change but possible moves not showing up from current position of white pawn. after that when one move caused the black pawn disappear.. 

https://user-images.githubusercontent.com/43809019/134199492-7df3bba1-1763-4d79-861c-f606d5e63d85.mp4

[chess_20210921204507.save.txt](https://github.com/madhaven/Chess.AI/files/7204366/chess_20210921204507.save.txt)
t

**Comment by zameel7** [comment]
@alansmathew might have encountered due to some error in En Passant rule ?

**Comment by madhaven** [comment]
This is an En Passant capture.
It's not an error
@alansmathew, <3 thank you broi

> En Passant is a fairly new addition to Chess that even I found out only recently.
> [wikipedia](https://en.wikipedia.org/wiki/En_passant), [chess.com](https://www.chess.com/terms/en-passant)
